name: test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
  gochk-goilerplate:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/resotto/gochk:latest
    steps:
      - name: Clone Goilerplate
        uses: actions/checkout@v2
        with:
          repository: resotto/goilerplate
      - name: Run Gochk
        run: |
          /go/bin/gochk -c=/go/src/github.com/resotto/gochk/configs/config.json
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run go test
        run: |
          go get -u gorm.io/gorm
          go get -u github.com/gin-gonic/gin
          go get -u github.com/google/uuid
          go get -u github.com/spf13/viper
          go get -u gorm.io/driver/postgres
          go test ./internal/app/...
